spring:
  application:
    name: ssoService
  datasource:
    url: jdbc:h2:mem:testdb  # In-memory database
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # Enable the H2 console for easy access
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8090

jwt:
  expiration:
    3600000
  secret:
    MySuperSecureSecretKeyForJWTsWithHS256!
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka